export { HomePage } from './HomePage'
export { TournamentsPage } from './TournamentsPage'
export { TeamsPage } from './TeamsPage'
export { MatchesPage } from './MatchesPage'
export { RegisterTeamPage } from './RegisterTeamPage'
export { InstructionsPage } from './InstructionsPage'
export { ProfilePage } from './ProfilePage'
