export { HomePage } from './HomePage'
export { TournamentsPage } from './TournamentsPage'
export { TeamsPage } from './TeamsPage'
export { MatchesPage } from './MatchesPage'
export { RegisterTeamPage } from './RegisterTeamPage'
